# Generated by Django 4.1.4 on 2022-12-20 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 2, 24, 32, 672337, tzinfo=datetime.timezone.utc)),
        ),
    ]
